name: Stage the app

on:
  push:
    types: [ labeled ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')
